### PR TITLE
Issue #44 - Memory footprint reductions and tweaks for AVR chips

### PR DESCRIPTION
**Pull request by zrecommerce**
See Issue #44.

### CODE REVIEW

**Comment by mjs513** [comment]
Hello Alex

I downloaded 1.6.7 yesterday and spent the whole day with revising affected libraries.   Since I could now selective merge changes I did it manually.

(1)   I could not agree  with changes to the AP_filter library.  I appears that your change to the AP_Filter lib for all boards except for the Intel Galileo. So I left the test in just for the Galileo.  If at some point the Galileo core changes I will delete the test.
(2)  As for the FreeIMU.h, I made the change to the Developer to Fabio and Me for version 2.
(3)  For FreeIMU.cpp I made all the changes except for incorporating the exclude_compass test.  Reason i did not is one you have it defaulted to exclude the compass where most people, including me, need the compass readings.  If you add the default so that the iHeading defaults to be included I would make the changes.  Seems like you are adding a whole lot of extra tests which will slow down the sketch.

I am thinking about creating a branch of library for the smaller boards so that i can incorporate some of these changes for those out there using the smaller boards.  However, this would be a future effort, especially since those smaller boards are being overtaken with new designs.

I will probably post the changes later today.

Thanks
Mike

**Comment by zrecommerce** [comment]
Hi Mike,

Thanks for having a look. I intended to leave iCompass included by default. iCompass should remain available by default, and is onky excluded if a developer explicitly defines EXCLUDE_ICOMPASS in their sketch.

```
#ifndef EXCLUDE_ICOMPASS
```
....should read as 'if EXLUDE_ICOMPASS is not defined, include this section when building'

**Comment by zrecommerce** [comment]
The changes to AP_Filter seemed to be the only way to get the FresIMU examples to compile on Arduino 1.6.7 ...maybe it's just me bowever. Where you able to vet a FreeIMU example to compile for an AVR device?

**Comment by zrecommerce** [comment]
Mind making a list of contributors? Perhaps a CONTRIBUTORS.md file?

**Comment by mjs513** [comment]
Hi Alex,
Just updated the FreeIMU library.  Can you repush the only the changes to FreeIMU.cpp and I will incorporate for you.

As to your other questions.  Yes it now compiles with AVR boards - I tested compiles with Arduino Leonardo and Mega2560.  Don't think a contributor.md file is needed. Reason, Github does it for you - see the top of the Library page.

**Pull request closed without merging**
