### PR TITLE
Filters + New Function getEstAltitude() + New Board (GY-88)

### PR DESCRIPTION
**Pull request by barzilaydn**
- Added a running average filter for heading (and made it like a compass)
- Added getEstAltitude() which uses a complementary filter of the
  barometer and accelerometer 
- Added a 1D Kalman Filter for the barometer pressure readings.

_all code is from the experimental processing sketch._

### CODE REVIEW

**Comment by MauroMombelli** [comment]
i'm working on some modification on DCM to clean sensor (basically tangential and circular acceleration compensation, but i'm having some problem there) and also some algoritm tyo automaticalli scale and center accelerometer and magnetometer fileter at startup.

is there a way to contact you, like a forum or similar?

**Comment by mjs513** [comment]
Happy New Year Mauro

Unfortunately I am not on a forum or have a separate blog from github.  I do have a email account that you can reach me on if you would like to do offline.  I can be reached at FreeIMU@aol.com if you would like.

Mike

**Comment by MauroMombelli** [comment]
Happy new Year!

what i'm working on is autocalibration (with a bit of user interaction, but is no-brain):

Gyroscope in my case have and hardcoded "bias", i enable it one axes at time, take some reading, and calculate the real sensor "center" value and real multiplication factor to have the right rad/s (bias has a know value). This happen in a matter of millliseconds, and the board should be still.

Magnetometer is relativtly easy as there are a lot of code around there, especially using a matrix to compenste soft irona and hard iron. Still looking for my own solution.

Accelerometer is quite difficult, my plan is to let the user move the board at every 6 position (up down, left right, point tail); (that is good because magnetometer will benefit from data on all position), data on axis will be valid only if stable value for a couple of seconds ll sensor value won't change a lot.

the idea is to exclude form DCM the magnetometer if its RAW vector lenght differ too much from starting value; this MAY be done also for accelerometer, but for it i would before try to compensate for circular and tangential error (obviously the distance from the sensor to the center of rotation should be known), this has varius benefit:

we exclude from error compensation data witch we already know is invalid; (dcm should return a lot better results, but i still have unconclusive data, as i'm actually working without calibratint the sensor reading)
compensating for circular motion acceleration will give more "pure" accelerometric data as only the linear acceleration (and G) should stay there;
not only altitude but TRANSLATION can be integrated (and cleaned using some GPS or other triangulation data, eventually)

please note that the filtering may use the same logic used by DCM; basically a second DCM witch work for translation istead of rotation;barometer is a lot similar to accelerometer, especially if not correctly protected from airflow; accelerometer will be the "base" as gyro are for rotation; GPS is like magnetomer, absolute data (the error can be considered absolute for samll amount of time and range, lets say 30min and <10.000m) but slow. But i don't think to have the knoledge to write this system alone.

That's why i hoped for a public discussion area where maybe someone will join the quest.

Maybe a discussion on the arduino forum or diydrones is good idea.

**Comment by mjs513** [comment]
Hi Mauro

I would suggest that you work within the DIY Drone forum.  There is a lot
of stuff already been done and posted on the forum on calibration and using
DCM.  There are a lot of smart people out there that could help you.  I am
on the forum but have not posted anything yet.

As for your simple calibration for the accel, gyro and mag there is already
a lot of stuff out there that should be of use to you including looking at
the Ardupilot code for how they do the calibration.  I have a few links
posted on the wiki page and can probably add more (freeimu) that may be of
help.

I do know in the ardupilot code the gps data is used to correct DCM ypr so
take a look.  GPS is pretty stable if you are working out doors.  With the
new ublox's you can sample GPS data pretty fast.

Mike

**Pull request closed without merging**
